version: "3.9"
services:
  s3:
    image: minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    networks:
      - internal
      - public
    volumes:
      - /data/docker/mlflow_minio:/data
  db:
    image: postgres:14
    restart: unless-stopped
    container_name: mlflow_db
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - /data/docker/mlflow_db:/var/lib/postgresql/data
    networks:
      - internal
  mlflow:
    image: mlflow_server
    container_name: tracker_mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USER}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PSWD}
    networks:
      - public
      - internal
    entrypoint: mlflow server --app-name basic-auth --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DATABASE} --default-artifact-root s3://${AWS_BUCKET_NAME}/ --artifacts-destination s3://${AWS_BUCKET_NAME}/ -h 0.0.0.0
    depends_on:
      - "db"

  create_s3_buckets:
    image: minio/mc
    depends_on:
      - "s3"
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://s3:9000 '${AWS_ACCESS_KEY_ID}' '${AWS_SECRET_ACCESS_KEY}') do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/${AWS_BUCKET_NAME};
      exit 0;
      "
    networks:
      - internal
  run_test_experiment:
    build:
      context: ./test_experiment
      dockerfile: Dockerfile
    platform: linux/amd64  # once continuumio/miniconda3:latest image work on native aarch64 (arm), remove this line 
    depends_on:
      - "mlflow"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    entrypoint: >
      /bin/sh -c "
      python3 mlflow_tracking.py;
      exit 0;
      "
    networks:
      - internal
networks:
  internal:
  public:
    driver: bridge
volumes:
  db_new_volume:
  minio_new_volume:
